; generated by PrusaSlicer 2.7.4+linux on 2026-07-23
EXCLUDE_OBJECT_DEFINE NAME=cube CENTER=110,110 POLYGON=[[90,90],[130,90],[130,130],[90,130]]
G21
G0 X90 Y90 Z0.2
;TYPE:External perimeter
EXCLUDE_OBJECT_START NAME=cube
G1 X90 Y90 E1 F1500
G1 X130 Y90 E2
G1 X130 Y130 E3
G1 X90 Y130 E4
G1 X90 Y90 E5
EXCLUDE_OBJECT_END NAME=cube
;TYPE:Internal infill
G1 X95 Y95 E10 F2400
G1 X125 Y95 E11
G1 X125 Y125 E12
G1 X95 Y125 E13
G1 X95 Y95 E14
; prusaslicer_config = begin
; bed_shape = 0x0,300x0,300x300,0x300
; gcode_flavor = klipper
; printer_model = Voron24
; prusaslicer_config = end
