/**
 * `.bgcode` decoder — phase 1 (DD-011): block walker + CRC32 + None/DEFLATE + None encoding.
 * Fixtures are assembled clean-room by the test helper (no PrusaSlicer, no AGPL code); phase 4 adds
 * real PrusaSlicer files for golden-equivalence.
 */
import { describe, expect, it } from 'vitest';
import { parseGcodeToIR } from '../../../gcode-parser/src/parse';
import { BgcodeBlockType, BgcodeCompression, BgcodeEncoding, openBgcode, sniffBgcode } from '../index.js';
import { assembleBgcode } from './assemble.js';

const enc = (s: string): Uint8Array => new TextEncoder().encode(s);
const dec = (b: Uint8Array): string => new TextDecoder().decode(b);
const GCODE = 'M83\nG1 X0 Y0 Z0.2 F1200\nG1 X10 Y0 E1\nG1 X10 Y10 E1\n';

describe('sniffBgcode', () => {
  it('matches the "GCDE" magic and the .bgcode extension', () => {
    expect(sniffBgcode(enc('GCDE....'))).toBe(true);
    expect(sniffBgcode(new Uint8Array(), 'model.bgcode')).toBe(true);
    expect(sniffBgcode(enc('; generated by PrusaSlicer'), 'model.gcode')).toBe(false);
  });
});

describe('openBgcode — decode (phase 1)', () => {
  it('decodes a None-compression / None-encoding GCode block to the original plain G-code', async () => {
    const buf = await assembleBgcode([
      {
        type: BgcodeBlockType.GCode,
        compression: BgcodeCompression.None,
        encoding: BgcodeEncoding.None,
        data: enc(GCODE)
      }
    ]);
    const { gcode, blocks, checksum } = await openBgcode(buf);
    expect(dec(gcode)).toBe(GCODE);
    expect(checksum).toBe('crc32');
    expect(blocks).toHaveLength(1);
  });

  it('decodes a DEFLATE-compressed GCode block (round-trips)', async () => {
    const buf = await assembleBgcode([
      {
        type: BgcodeBlockType.GCode,
        compression: BgcodeCompression.Deflate,
        encoding: BgcodeEncoding.None,
        data: enc(GCODE)
      }
    ]);
    const { gcode } = await openBgcode(buf);
    expect(dec(gcode)).toBe(GCODE);
  });

  it('concatenates multiple GCode blocks in file order and walks past metadata/thumbnail blocks', async () => {
    const buf = await assembleBgcode([
      {
        type: BgcodeBlockType.FileMetadata,
        compression: BgcodeCompression.None,
        encoding: 0,
        data: enc('printer=MK4\n')
      },
      {
        type: BgcodeBlockType.Thumbnail,
        compression: BgcodeCompression.None,
        thumbnail: { format: 0, width: 2, height: 2 },
        data: enc('PNGDATA!')
      },
      { type: BgcodeBlockType.GCode, compression: BgcodeCompression.Deflate, encoding: 0, data: enc('G1 X1\n') },
      { type: BgcodeBlockType.GCode, compression: BgcodeCompression.None, encoding: 0, data: enc('G1 X2\n') }
    ]);
    const { gcode, blocks } = await openBgcode(buf);
    expect(dec(gcode)).toBe('G1 X1\nG1 X2\n'); // only the two GCode blocks, in order
    expect(blocks.map((b) => b.type)).toEqual([0, 5, 1, 1]); // all four walked
  });

  it('decodes a file with no per-block checksum', async () => {
    const buf = await assembleBgcode(
      [{ type: BgcodeBlockType.GCode, compression: BgcodeCompression.None, encoding: 0, data: enc(GCODE) }],
      { checksum: 'none' }
    );
    const { gcode, checksum } = await openBgcode(buf);
    expect(dec(gcode)).toBe(GCODE);
    expect(checksum).toBe('none');
  });

  it('end-to-end: the decoded G-code parses into a valid IR (→ parser)', async () => {
    const buf = await assembleBgcode([
      { type: BgcodeBlockType.GCode, compression: BgcodeCompression.Deflate, encoding: 0, data: enc(GCODE) }
    ]);
    const { gcode } = await openBgcode(buf);
    const { ir } = parseGcodeToIR(dec(gcode));
    expect(ir.segments.count).toBe(3);
    expect(ir.header.capabilities.geometry).toBe('known');
  });
});

describe('openBgcode — honest rejection & bounds', () => {
  it('rejects a bad magic', async () => {
    const buf = await assembleBgcode([{ type: 1, compression: 0, encoding: 0, data: enc('G1\n') }], { magic: 'XXXX' });
    await expect(openBgcode(buf)).rejects.toMatchObject({ code: 'E_BGCODE_MAGIC' });
  });

  it('rejects an unsupported version', async () => {
    const buf = await assembleBgcode([{ type: 1, compression: 0, encoding: 0, data: enc('G1\n') }], { version: 2 });
    await expect(openBgcode(buf)).rejects.toMatchObject({ code: 'E_BGCODE_VERSION' });
  });

  it('rejects a corrupted block (CRC32 mismatch)', async () => {
    const buf = await assembleBgcode([{ type: 1, compression: BgcodeCompression.None, encoding: 0, data: enc(GCODE) }]);
    buf[20] ^= 0xff; // flip a payload byte
    await expect(openBgcode(buf)).rejects.toMatchObject({ code: 'E_BGCODE_CRC' });
  });

  it('rejects a truncated file', async () => {
    const buf = await assembleBgcode([{ type: 1, compression: 0, encoding: 0, data: enc(GCODE) }]);
    await expect(openBgcode(buf.subarray(0, 14))).rejects.toMatchObject({ code: 'E_BGCODE_TRUNCATED' });
  });

  it('honestly rejects an unknown compression id', async () => {
    // compression id 7 is outside the spec enum (0..3) — bounded structured error, not a guess.
    const bad = await assembleBgcode([{ type: 1, compression: 7, encoding: 0, data: enc(GCODE) }]);
    await expect(openBgcode(bad)).rejects.toMatchObject({ code: 'E_BGCODE_UNSUPPORTED_COMPRESSION' });
  });

  it('enforces the output-bytes cap (decompression-bomb defense)', async () => {
    const buf = await assembleBgcode([{ type: 1, compression: BgcodeCompression.None, encoding: 0, data: enc(GCODE) }]);
    await expect(openBgcode(buf, { maxOutputBytes: 4 })).rejects.toMatchObject({ code: /E_BGCODE_(BOMB|SIZE)/ });
  });
});
