// @vitest-environment node
/*
 * Real-worker contract (DD-007 §4.5): a genuine parse through the INSTALLED tarballs —
 * GcodeParseSession over a node:worker_threads worker running the batteries-equivalent
 * entry (dialects + containers from tarballs). No stubs below the session boundary.
 */
import { describe, expect, it } from 'vitest';
import { Worker } from 'node:worker_threads';
import { fileURLToPath } from 'node:url';
import { GcodeParseSession } from '@chestnutlabs/gcode-parser';
import { createProgressMapper, segmentAtByte } from '@chestnutlabs/toolpath-core';

/** Adapt node:worker_threads to the session's WorkerLike contract. */
class NodeWorkerAdapter {
  onmessage = null;
  onerror = null;
  constructor(entryUrl) {
    this.w = new Worker(fileURLToPath(entryUrl));
    this.w.on('message', (data) => this.onmessage?.({ data }));
    this.w.on('error', (err) => this.onerror?.(err));
  }
  postMessage(msg, transfer) {
    this.w.postMessage(msg, transfer ?? []);
  }
  terminate() {
    void this.w.terminate();
  }
}

const GCODE = [
  '; generated by PrusaSlicer 2.7.0 on 2026-07-23',
  '; bed_shape = 0x0,250x0,250x210,0x210',
  'G21',
  'G90',
  'G1 Z0.2 F600',
  ';TYPE:Perimeter',
  'G1 X10 Y10 E1 F1200',
  'G1 X20 Y10 E2',
  'G1 X20 Y20 E3',
  'G1 X10 Y20 E4',
  'G1 Z0.4',
  ';TYPE:Infill',
  'G1 X20 Y20 E5',
  'G1 X10 Y10 E6',
  ''
].join('\n');

describe('consumer fixture — real worker parse from installed tarballs', () => {
  it('parses G-code end to end incl. dialect annotation and progress mapping', async () => {
    const session = new GcodeParseSession({
      worker: () => new NodeWorkerAdapter(new URL('./worker-node-entry.mjs', import.meta.url))
    });
    try {
      const bytes = new TextEncoder().encode(GCODE);
      const total = bytes.byteLength;
      const result = await session.parse(bytes, { dialects: 'auto' });
      expect(result.ir.segments.count).toBeGreaterThan(0);
      expect(result.ir.layers.length).toBeGreaterThanOrEqual(2);
      // Dialect adapter ran inside the worker: PrusaSlicer feature roles annotated.
      expect(result.ir.header.capabilities.featureRoles).not.toBe('unavailable');
      // Bed geometry discovered from bed_shape (DD-005) and delivered via metadata.
      expect(result.metadata?.machine?.bed).toBeDefined();
      // DD-006 chain works on the delivered IR (sourceIndex transferred intact).
      const mapper = createProgressMapper(result.ir, { fileSizeBytes: total });
      const mapped = mapper.observe({ v: 1, timestampMs: 1, position: { percent: 0.9, percentBasis: 'bytes' } });
      expect(mapped.confidence).toBe('approximated');
      expect(mapped.segIndex).not.toBeNull();
      expect(segmentAtByte(result.ir.sourceIndex, total)).toBe(result.ir.segments.count - 1);
    } finally {
      session.dispose();
    }
  });
});
