/**
 * OrcaSlicer / Bambu Studio dialect adapter (DD-005 phase 3, issue #75).
 *
 * Annotates: feature roles from `; FEATURE:` (Bambu Studio) **or** `;TYPE:`
 * (real OrcaSlicer / AnycubicSlicerNext — same vocabulary, different prefix;
 * RR-007 §5.8) → `featureRoles: 'known'`; object start/stop comments across all
 * lineage formats (Bambu `start printing object, unique label id:`, Orca
 * `printing object <name> id:<id>`) → `object` channel + `objects: 'known'`; bed geometry
 * from `printable_area` config comments (bare .gcode files — inside a
 * `.gcode.3mf` the container's machine config already provides `known`
 * geometry and outranks this), and printer identity. Detection also accepts
 * container metadata as evidence (DD-005 §4.1 DetectInput.containerMeta).
 */
import { FeatureRole, type ToolpathIR } from '@chestnutlabs/toolpath-core';
import type { AnnotationSink, DialectAdapter } from './contracts.js';
import { parseFilamentTotals, parseHmsToSeconds } from './prusaslicer.js';
import { PrintingObjectTracker } from './object-markers.js';
import {
  ThumbnailCollector,
  applyMarkerRanges,
  applyWipeRanges,
  bedFromPoints,
  matchWipeComment,
  parseAreaPoints,
  parseKeyValue,
  type RangeMarker,
  type WipeMark
} from './annotate.js';

/** Orca/Bambu `; FEATURE:` names → DD-001 FeatureRole. */
const FEATURE_MAP: Record<string, number> = {
  'inner wall': FeatureRole.Perimeter,
  'outer wall': FeatureRole.ExternalPerimeter,
  'overhang wall': FeatureRole.Perimeter,
  'sparse infill': FeatureRole.Infill,
  'internal solid infill': FeatureRole.SolidInfill,
  'top surface': FeatureRole.SolidInfill,
  'bottom surface': FeatureRole.SolidInfill,
  ironing: FeatureRole.SolidInfill,
  bridge: FeatureRole.Bridge,
  support: FeatureRole.Support,
  'support interface': FeatureRole.Support,
  'support transition': FeatureRole.Support,
  skirt: FeatureRole.Skirt,
  brim: FeatureRole.Brim,
  'prime tower': FeatureRole.Custom,
  'gap infill': FeatureRole.Infill,
  'internal bridge': FeatureRole.Bridge,
  custom: FeatureRole.Custom
};

interface OrcaState {
  features: RangeMarker[];
  wipes: WipeMark[];
  objectTracker: PrintingObjectTracker;
  bedPoints: string | null;
  bedSrcByte?: number;
  heightMm?: number;
  printerModel?: string;
  filamentTypes?: string[];
  filamentColours?: string[];
  thumbs: ThumbnailCollector;
}

const state = new WeakMap<AnnotationSink, OrcaState>();

function stateFor(sink: AnnotationSink): OrcaState {
  let s = state.get(sink);
  if (s === undefined) {
    s = {
      features: [],
      wipes: [],
      objectTracker: new PrintingObjectTracker(),
      bedPoints: null,
      thumbs: new ThumbnailCollector()
    };
    state.set(sink, s);
  }
  return s;
}

export function orcaBambu(): DialectAdapter {
  return {
    id: 'orca-bambu',
    displayName: 'OrcaSlicer / Bambu Studio',
    kind: 'slicer',
    detect(input) {
      const m = /(BambuStudio[^\n\r]*|generated by OrcaSlicer[^\n\r]*)/.exec(input.headText);
      if (m !== null) {
        return { dialectId: 'orca-bambu', kind: 'slicer', confidence: 'known', evidence: `header: ${m[1].trim()}` };
      }
      if (input.containerMeta !== undefined && input.containerMeta['printer_model'] !== undefined) {
        return {
          dialectId: 'orca-bambu',
          kind: 'slicer',
          confidence: 'inferred',
          evidence: `container metadata: printer_model=${input.containerMeta['printer_model']}`
        };
      }
      return null;
    },
    onComment(comment, srcByte, sink) {
      const s = stateFor(sink);
      const trimmed = comment.trim();
      // Feature roles: Bambu Studio emits `; FEATURE:<vocab>`; real OrcaSlicer / AnycubicSlicerNext
      // emit `;TYPE:<vocab>` — the same Orca vocabulary, different prefix (RR-007 §5.8). Accept both.
      const featureName = trimmed.startsWith('FEATURE:')
        ? trimmed.slice(8)
        : trimmed.startsWith('TYPE:')
          ? trimmed.slice(5)
          : null;
      if (featureName !== null) {
        const role = FEATURE_MAP[featureName.trim().toLowerCase()];
        s.features.push({ srcByte, value: role ?? FeatureRole.Custom });
        return;
      }
      // Object membership across all lineage formats (shared object-marker parser).
      if (s.objectTracker.handle(trimmed, srcByte)) return;
      const wipe = matchWipeComment(comment);
      if (wipe !== null) {
        s.wipes.push({ srcByte, open: wipe === 'start' });
        return;
      }
      if (s.thumbs.isActive || trimmed.toLowerCase().startsWith('thumbnail')) {
        s.thumbs.feed(comment, sink);
        return;
      }
      // Orca/Bambu print-time comments are colon-separated (`; total estimated time: 1h 2m 3s`).
      const timeMatch = /^(?:total estimated time|model printing time)\s*:\s*(.+)$/i.exec(trimmed);
      if (timeMatch !== null) {
        const sec = parseHmsToSeconds(timeMatch[1]);
        if (sec !== null) {
          sink.setPrintEstimate({
            seconds: sec,
            source: { adapterId: 'orca-bambu', evidence: `; ${trimmed}`, srcByte }
          });
        }
        return;
      }
      if (parseFilamentTotals(comment, srcByte, 'orca-bambu', sink)) return;
      const kv = parseKeyValue(comment);
      if (kv === null) return;
      if (kv.key === 'printable_area') {
        s.bedPoints = kv.value;
        s.bedSrcByte = srcByte;
      } else if (kv.key === 'printable_height') {
        const h = parseFloat(kv.value);
        if (Number.isFinite(h)) s.heightMm = h;
      } else if (kv.key === 'printer_model') {
        s.printerModel = kv.value;
      } else if (kv.key === 'filament_type') {
        s.filamentTypes = kv.value.split(';').map((v) => v.trim());
      } else if (kv.key === 'filament_colour') {
        s.filamentColours = kv.value.split(';').map((v) => v.trim());
      }
    },
    finalize(ir: ToolpathIR, sink) {
      const s = stateFor(sink);
      const features = applyMarkerRanges(ir, s.features, (a, b, v) => sink.setFeature(a, b, v));
      if (features > 0) sink.upgradeCapability('featureRoles', 'known');
      s.objectTracker.apply(ir, sink);
      if (applyWipeRanges(ir, s.wipes, sink) > 0) sink.upgradeCapability('wipeMoves', 'known');
      if (s.bedPoints !== null) {
        const points = parseAreaPoints(s.bedPoints);
        if (points !== null) {
          sink.setMachine(
            bedFromPoints(
              points,
              'orca-bambu',
              '; printable_area config comment',
              s.heightMm,
              s.printerModel,
              s.bedSrcByte
            )
          );
        } else {
          sink.warn('dialect-bed-unparsed', 'printable_area comment present but unparseable');
        }
      }
      if (s.printerModel !== undefined) sink.setRaw('printer_model', s.printerModel);
      // Multi-tool/AMS metadata (phase 5): filament slots enrich ir.tools.
      const slots = Math.max(s.filamentTypes?.length ?? 0, s.filamentColours?.length ?? 0);
      for (let i = 0; i < Math.min(slots, 64); i++) {
        sink.setFilament({ slot: i, type: s.filamentTypes?.[i], color: s.filamentColours?.[i] });
        sink.setToolInfo(i, { material: s.filamentTypes?.[i], colorHex: s.filamentColours?.[i] });
      }
    }
  };
}
