/**
 * OrcaSlicer / Bambu Studio dialect adapter (DD-005 phase 3, issue #75).
 *
 * Annotates: `; FEATURE:` roles (→ `featureRoles: 'known'`), Bambu object
 * start/stop comments (→ `object` channel + `objects: 'known'`), bed geometry
 * from `printable_area` config comments (bare .gcode files — inside a
 * `.gcode.3mf` the container's machine config already provides `known`
 * geometry and outranks this), and printer identity. Detection also accepts
 * container metadata as evidence (DD-005 §4.1 DetectInput.containerMeta).
 */
import { FeatureRole, type ToolpathIR } from '@chestnutlabs/toolpath-core';
import type { AnnotationSink, DialectAdapter } from './contracts.js';
import {
  ThumbnailCollector,
  applyMarkerRanges,
  bedFromPoints,
  parseAreaPoints,
  parseKeyValue,
  type RangeMarker
} from './annotate.js';

/** Orca/Bambu `; FEATURE:` names → DD-001 FeatureRole. */
const FEATURE_MAP: Record<string, number> = {
  'inner wall': FeatureRole.Perimeter,
  'outer wall': FeatureRole.ExternalPerimeter,
  'overhang wall': FeatureRole.Perimeter,
  'sparse infill': FeatureRole.Infill,
  'internal solid infill': FeatureRole.SolidInfill,
  'top surface': FeatureRole.SolidInfill,
  'bottom surface': FeatureRole.SolidInfill,
  ironing: FeatureRole.SolidInfill,
  bridge: FeatureRole.Bridge,
  support: FeatureRole.Support,
  'support interface': FeatureRole.Support,
  'support transition': FeatureRole.Support,
  skirt: FeatureRole.Skirt,
  brim: FeatureRole.Brim,
  'prime tower': FeatureRole.Custom,
  'gap infill': FeatureRole.Infill,
  custom: FeatureRole.Custom
};

interface OrcaState {
  features: RangeMarker[];
  objects: RangeMarker[];
  objectNames: Map<number, string>;
  bedPoints: string | null;
  bedSrcByte?: number;
  heightMm?: number;
  printerModel?: string;
  thumbs: ThumbnailCollector;
}

const state = new WeakMap<AnnotationSink, OrcaState>();

function stateFor(sink: AnnotationSink): OrcaState {
  let s = state.get(sink);
  if (s === undefined) {
    s = { features: [], objects: [], objectNames: new Map(), bedPoints: null, thumbs: new ThumbnailCollector() };
    state.set(sink, s);
  }
  return s;
}

export function orcaBambu(): DialectAdapter {
  return {
    id: 'orca-bambu',
    displayName: 'OrcaSlicer / Bambu Studio',
    kind: 'slicer',
    detect(input) {
      const m = /(BambuStudio[^\n\r]*|generated by OrcaSlicer[^\n\r]*)/.exec(input.headText);
      if (m !== null) {
        return { dialectId: 'orca-bambu', kind: 'slicer', confidence: 'known', evidence: `header: ${m[1].trim()}` };
      }
      if (input.containerMeta !== undefined && input.containerMeta['printer_model'] !== undefined) {
        return {
          dialectId: 'orca-bambu',
          kind: 'slicer',
          confidence: 'inferred',
          evidence: `container metadata: printer_model=${input.containerMeta['printer_model']}`
        };
      }
      return null;
    },
    onComment(comment, srcByte, sink) {
      const s = stateFor(sink);
      const trimmed = comment.trim();
      if (trimmed.startsWith('FEATURE:')) {
        const role = FEATURE_MAP[trimmed.slice(8).trim().toLowerCase()];
        s.features.push({ srcByte, value: role ?? FeatureRole.Custom });
        return;
      }
      const start = /^start printing object,?\s*(?:unique\s+)?id:?\s*(\d+)(?:\s+name:\s*(.+))?/i.exec(trimmed);
      if (start !== null) {
        const value = parseInt(start[1]) + 1; // object channel is 1-based (0 = none)
        s.objects.push({ srcByte, value });
        if (start[2] !== undefined) s.objectNames.set(value, start[2].trim());
        return;
      }
      if (/^stop printing object/i.test(trimmed)) {
        s.objects.push({ srcByte, value: 0 }); // range terminator
        return;
      }
      if (s.thumbs.isActive || trimmed.toLowerCase().startsWith('thumbnail')) {
        s.thumbs.feed(comment, sink);
        return;
      }
      const kv = parseKeyValue(comment);
      if (kv === null) return;
      if (kv.key === 'printable_area') {
        s.bedPoints = kv.value;
        s.bedSrcByte = srcByte;
      } else if (kv.key === 'printable_height') {
        const h = parseFloat(kv.value);
        if (Number.isFinite(h)) s.heightMm = h;
      } else if (kv.key === 'printer_model') {
        s.printerModel = kv.value;
      }
    },
    finalize(ir: ToolpathIR, sink) {
      const s = stateFor(sink);
      const features = applyMarkerRanges(ir, s.features, (a, b, v) => sink.setFeature(a, b, v));
      if (features > 0) sink.upgradeCapability('featureRoles', 'known');
      const objects = applyMarkerRanges(ir, s.objects, (a, b, v) => sink.setObject(a, b, v));
      if (objects > 0) {
        for (const [value, name] of s.objectNames) sink.defineObject(value, name);
        sink.upgradeCapability('objects', 'known');
      }
      if (s.bedPoints !== null) {
        const points = parseAreaPoints(s.bedPoints);
        if (points !== null) {
          sink.setMachine(
            bedFromPoints(
              points,
              'orca-bambu',
              '; printable_area config comment',
              s.heightMm,
              s.printerModel,
              s.bedSrcByte
            )
          );
        } else {
          sink.warn('dialect-bed-unparsed', 'printable_area comment present but unparseable');
        }
      }
      if (s.printerModel !== undefined) sink.setRaw('printer_model', s.printerModel);
    }
  };
}
