/**
 * PrusaSlicer dialect adapter (DD-005 phase 3, issue #75).
 *
 * Annotates: `;TYPE:` feature roles (→ `featureRoles: 'known'`), bed geometry
 * from the settings-block comments (`bed_shape`, `max_print_height`,
 * `printer_model` — confidence `inferred`, provenance recorded), and bounded
 * `; thumbnail begin/end` PNG thumbnails. Geometry is untouchable by contract.
 */
import { FeatureRole, type ToolpathIR } from '@chestnutlabs/toolpath-core';
import type { AnnotationSink, DialectAdapter } from './contracts.js';
import {
  ThumbnailCollector,
  applyMarkerRanges,
  bedFromPoints,
  parseAreaPoints,
  parseKeyValue,
  type RangeMarker
} from './annotate.js';

/** Prusa `;TYPE:` names → DD-001 FeatureRole (unknown names → Custom, honestly generic). */
const TYPE_MAP: Record<string, number> = {
  perimeter: FeatureRole.Perimeter,
  'external perimeter': FeatureRole.ExternalPerimeter,
  'overhang perimeter': FeatureRole.Perimeter,
  'internal infill': FeatureRole.Infill,
  'solid infill': FeatureRole.SolidInfill,
  'top solid infill': FeatureRole.SolidInfill,
  'bridge infill': FeatureRole.Bridge,
  'internal bridge infill': FeatureRole.Bridge,
  'support material': FeatureRole.Support,
  'support material interface': FeatureRole.Support,
  'skirt/brim': FeatureRole.Skirt,
  skirt: FeatureRole.Skirt,
  brim: FeatureRole.Brim,
  'wipe tower': FeatureRole.Custom,
  custom: FeatureRole.Custom
};

interface PrusaState {
  markers: RangeMarker[];
  bedPoints: string | null;
  bedSrcByte?: number;
  heightMm?: number;
  printerModel?: string;
  thumbs: ThumbnailCollector;
}

const state = new WeakMap<AnnotationSink, PrusaState>();

function stateFor(sink: AnnotationSink): PrusaState {
  let s = state.get(sink);
  if (s === undefined) {
    s = { markers: [], bedPoints: null, thumbs: new ThumbnailCollector() };
    state.set(sink, s);
  }
  return s;
}

export function prusaSlicer(): DialectAdapter {
  return {
    id: 'prusaslicer',
    displayName: 'PrusaSlicer',
    kind: 'slicer',
    detect(input) {
      const m = /generated by (PrusaSlicer[^\n\r]*)/.exec(input.headText);
      if (m !== null) {
        return { dialectId: 'prusaslicer', kind: 'slicer', confidence: 'known', evidence: `header: ${m[1].trim()}` };
      }
      // Settings live at the tail; a tail-only match still identifies the file.
      if (/;\s*generated by PrusaSlicer/.test(input.tailText) || /\n;\s*bed_shape\s*=/.test(input.tailText)) {
        return { dialectId: 'prusaslicer', kind: 'slicer', confidence: 'inferred', evidence: 'settings block (tail)' };
      }
      return null;
    },
    onComment(comment, srcByte, sink) {
      const s = stateFor(sink);
      if (comment.startsWith('TYPE:')) {
        const role = TYPE_MAP[comment.slice(5).trim().toLowerCase()];
        s.markers.push({ srcByte, value: role ?? FeatureRole.Custom });
        return;
      }
      if (s.thumbs.isActive || comment.trimStart().toLowerCase().startsWith('thumbnail')) {
        s.thumbs.feed(comment, sink);
        return;
      }
      const kv = parseKeyValue(comment);
      if (kv === null) return;
      if (kv.key === 'bed_shape') {
        s.bedPoints = kv.value;
        s.bedSrcByte = srcByte;
      } else if (kv.key === 'max_print_height') {
        const h = parseFloat(kv.value);
        if (Number.isFinite(h)) s.heightMm = h;
      } else if (kv.key === 'printer_model') {
        s.printerModel = kv.value;
      }
    },
    finalize(ir: ToolpathIR, sink) {
      const s = stateFor(sink);
      const applied = applyMarkerRanges(ir, s.markers, (a, b, v) => sink.setFeature(a, b, v));
      if (applied > 0) sink.upgradeCapability('featureRoles', 'known');
      if (s.bedPoints !== null) {
        const points = parseAreaPoints(s.bedPoints);
        if (points !== null) {
          sink.setMachine(
            bedFromPoints(
              points,
              'prusaslicer',
              '; bed_shape settings comment',
              s.heightMm,
              s.printerModel,
              s.bedSrcByte
            )
          );
        } else {
          sink.warn('dialect-bed-unparsed', 'bed_shape comment present but unparseable');
        }
      }
      if (s.printerModel !== undefined) sink.setRaw('printer_model', s.printerModel);
    }
  };
}
