/**
 * Simplify3D dialect adapter (DD-026 T1, RR-007 §5.5).
 *
 * Annotates `; feature <lowercase token>` roles — Simplify3D's lowercase feature vocabulary. There is
 * NO object-membership channel in Simplify3D output (RR-007 §5.5): the prime line is arbitrary
 * Starting-Script geometry and the prime pillar / ooze shield are feature roles, not object brackets.
 * So `objects` stays honestly `unavailable` and framing falls back to feature-role classification
 * (DD-026 T2), never a fabricated membership. Simplify3D emits Marlin-flavoured motion; the marlin
 * firmware adapter composes for firmware identity.
 */
import { FeatureRole, type ToolpathIR } from '@chestnutlabs/toolpath-core';
import type { AnnotationSink, DialectAdapter } from './contracts.js';
import { applyMarkerRanges, type RangeMarker } from './annotate.js';

/** Simplify3D `; feature <token>` names → DD-001 FeatureRole (unknown names → Custom, honestly generic). */
const FEATURE_MAP: Record<string, number> = {
  skirt: FeatureRole.Skirt,
  brim: FeatureRole.Brim,
  raft: FeatureRole.Raft,
  'outer perimeter': FeatureRole.ExternalPerimeter,
  'inner perimeter': FeatureRole.Perimeter,
  perimeter: FeatureRole.Perimeter,
  infill: FeatureRole.Infill,
  'solid layer': FeatureRole.SolidInfill,
  'gap fill': FeatureRole.SolidInfill,
  support: FeatureRole.Support,
  'dense support': FeatureRole.Support,
  bridge: FeatureRole.Bridge,
  'prime pillar': FeatureRole.PrimeTower,
  // Ooze shield is an unmapped housekeeping wall — kept as generic `Custom` (stays in-frame, the safe
  // direction per DD-026 §13) rather than guessed into a tower/purge role.
  'ooze shield': FeatureRole.Custom
};

interface Simplify3dState {
  markers: RangeMarker[];
}

const state = new WeakMap<AnnotationSink, Simplify3dState>();

function stateFor(sink: AnnotationSink): Simplify3dState {
  let s = state.get(sink);
  if (s === undefined) {
    s = { markers: [] };
    state.set(sink, s);
  }
  return s;
}

export function simplify3d(): DialectAdapter {
  return {
    id: 'simplify3d',
    displayName: 'Simplify3D',
    kind: 'slicer',
    detect(input) {
      const m = /generated by (Simplify3D[^\n\r]*)/i.exec(input.headText);
      if (m !== null) {
        return { dialectId: 'simplify3d', kind: 'slicer', confidence: 'known', evidence: `header: ${m[1].trim()}` };
      }
      return null;
    },
    onComment(comment, srcByte, sink) {
      const s = stateFor(sink);
      // Space-prefixed lowercase feature comment: `; feature outer perimeter`. The leading space is
      // already stripped by the parser before onComment, so `comment` begins `feature `.
      const trimmed = comment.trim();
      if (/^feature\b/i.test(trimmed)) {
        const token = trimmed.slice('feature'.length).trim().toLowerCase();
        const role = FEATURE_MAP[token];
        s.markers.push({ srcByte, value: role ?? FeatureRole.Custom });
      }
    },
    finalize(ir: ToolpathIR, sink) {
      const s = stateFor(sink);
      const applied = applyMarkerRanges(ir, s.markers, (a, b, v) => sink.setFeature(a, b, v));
      if (applied > 0) sink.upgradeCapability('featureRoles', 'known');
    }
  };
}
