/**
 * DD-005 phase 1 integration (#73): parse-core hooks, worker/session wiring of
 * serializable dialect selection, and the GEOMETRY-INVARIANCE GATE — adapters
 * annotate; they can never reshape the toolpath.
 */
import { describe, expect, it } from 'vitest';
import { FeatureRole, type ToolpathIR } from '@chestnutlabs/toolpath-core';
import { createDialectRunner, type DialectAdapter } from '@chestnutlabs/gcode-dialects';
import { parseGcodeToIR, type CommandEvent } from '../parse';
import { createWorkerHandler, type WorkerHandlerOptions } from '../worker-core';
import { GcodeParseSession, type WorkerLike } from '../session';
import type { WorkerRequest } from '../protocol';

const GCODE = [
  '; generated by TestSlicer 1.0',
  'G0 X10 Y10 Z0.2',
  ';TYPE:External perimeter',
  'G1 X20 Y10 E1 F1500',
  'G1 X20 Y20 E2',
  'M486 S1',
  ';TYPE:Infill',
  'G1 X10 Y20 E3',
  'G1 X10 Y10 E4',
  'M486 S-1'
].join('\n');

/** Test adapter: features from ;TYPE:, objects from M486 via the command hook. */
const testAdapter: DialectAdapter = {
  id: 'testslicer',
  displayName: 'Test Slicer',
  kind: 'slicer',
  detect: (input) =>
    input.headText.includes('generated by TestSlicer')
      ? { dialectId: 'testslicer', kind: 'slicer', confidence: 'known', evidence: 'header comment' }
      : null,
  onCommand(event, sink) {
    if (event.gcode === 'm486' && event.params.s !== undefined && event.params.s >= 0) {
      sink.setObject(event.segIndex, event.segIndex + 1, event.params.s + 1);
      sink.defineObject(event.params.s + 1, `object ${event.params.s}`);
      sink.upgradeCapability('objects', 'known');
    }
  },
  finalize(ir, sink) {
    sink.setFeature(0, ir.segments.count - 1, FeatureRole.ExternalPerimeter);
    sink.upgradeCapability('featureRoles', 'known');
    sink.setMachine({
      bed: { kind: 'rect', min: { x: 0, y: 0 }, max: { x: 220, y: 220 } },
      origin: { x: 0, y: 0 },
      confidence: 'inferred',
      source: { adapterId: 'testslicer', evidence: 'test' }
    });
  }
};

function loopbackWorker(opts?: WorkerHandlerOptions): WorkerLike {
  const w: WorkerLike = { onmessage: null, onerror: null, postMessage: () => undefined, terminate: () => undefined };
  const handler = createWorkerHandler((msg) => {
    void Promise.resolve().then(() => w.onmessage?.({ data: msg }));
  }, opts);
  w.postMessage = (m: unknown) => handler(m as WorkerRequest);
  return w;
}

const GEOMETRY_CHANNELS = ['x0', 'y0', 'z0', 'x1', 'y1', 'z1', 'e', 'kind', 'layer', 'srcByte'] as const;

function geometryDigest(ir: ToolpathIR): string {
  return GEOMETRY_CHANNELS.map((ch) => {
    // FNV-1a over the raw bytes of each channel.
    const bytes = new Uint8Array(ir.segments[ch].buffer, ir.segments[ch].byteOffset, ir.segments[ch].byteLength);
    let h = 0x811c9dc5;
    for (let i = 0; i < bytes.length; i++) {
      h ^= bytes[i];
      h = Math.imul(h, 0x01000193);
    }
    return (h >>> 0).toString(16);
  }).join(':');
}

describe('dialect wiring + geometry invariance (#73)', () => {
  it('parse-core hooks observe comments and normalized commands', () => {
    const comments: string[] = [];
    const commands: CommandEvent[] = [];
    parseGcodeToIR(GCODE, {
      onComment: (text) => comments.push(text),
      onCommand: (e) => commands.push(e)
    });
    expect(comments).toContain('TYPE:External perimeter');
    expect(comments).toContain('TYPE:Infill');
    const m486 = commands.filter((c) => c.gcode === 'm486');
    expect(m486.length).toBe(2);
    expect(m486[0].params.s).toBe(1);
    expect(m486[0].segIndex).toBeGreaterThan(0);
  });

  it('GEOMETRY-INVARIANCE GATE: adapters cannot change the toolpath (digest-identical)', async () => {
    const runner = createDialectRunner([testAdapter]);
    const withAdapters = new GcodeParseSession({ worker: loopbackWorker({ dialects: runner }) });
    const without = new GcodeParseSession({ worker: loopbackWorker() });

    const annotated = await withAdapters.parse(GCODE, { yieldIntervalMs: 5 });
    const plain = await without.parse(GCODE, { yieldIntervalMs: 5 });

    expect(geometryDigest(annotated.ir)).toBe(geometryDigest(plain.ir));
    expect(annotated.ir.segments.count).toBe(plain.ir.segments.count);
    // ...while annotations ARE present on the adapter run only.
    expect(annotated.ir.header.capabilities.featureRoles).toBe('known');
    expect(plain.ir.header.capabilities.featureRoles).toBe('unavailable');
    withAdapters.dispose();
    without.dispose();
  });

  it('worker/session: metadata + dialects header arrive; selection + config are wire-serializable', async () => {
    const session = new GcodeParseSession({ worker: loopbackWorker({ dialects: createDialectRunner([testAdapter]) }) });
    const result = await session.parse(GCODE, { yieldIntervalMs: 5, dialects: ['testslicer'] });
    expect(result.metadata?.dialects?.[0].dialectId).toBe('testslicer');
    expect(result.metadata?.machine?.bed.kind).toBe('rect');
    expect(result.ir.header.dialects[0]).toEqual({ id: 'testslicer', confidence: 'known' });
    expect(result.ir.segments.feature[0]).toBe(FeatureRole.ExternalPerimeter);
    expect(Array.from(result.ir.segments.object).some((v) => v === 2)).toBe(true);
    session.dispose();
  });

  it('dialects:false disables annotation; unmatched detection leaves everything untouched', async () => {
    const session = new GcodeParseSession({ worker: loopbackWorker({ dialects: createDialectRunner([testAdapter]) }) });
    const off = await session.parse(GCODE, { yieldIntervalMs: 5, dialects: false });
    expect(off.metadata).toBeUndefined();
    expect(off.ir.header.capabilities.featureRoles).toBe('unavailable');
    session.dispose();

    const session2 = new GcodeParseSession({
      worker: loopbackWorker({ dialects: createDialectRunner([testAdapter]) })
    });
    const unmatched = await session2.parse('G0 X1 Y1\nG1 X2 Y2 E1', { yieldIntervalMs: 5 });
    expect(unmatched.metadata).toBeUndefined();
    expect(unmatched.ir.header.dialects).toEqual([]);
    session2.dispose();
  });

  it('slim worker: explicit dialect request degrades VISIBLY (dialects-unavailable)', async () => {
    const session = new GcodeParseSession({ worker: loopbackWorker() }); // no runner = slim
    const explicit = await session.parse(GCODE, { yieldIntervalMs: 5, dialects: ['testslicer'] });
    expect(explicit.ir.header.warnings.some((w) => w.code === 'dialects-unavailable')).toBe(true);
    session.dispose();

    // Default 'auto' against slim stays silent — nothing was requested.
    const session2 = new GcodeParseSession({ worker: loopbackWorker() });
    const auto = await session2.parse(GCODE, { yieldIntervalMs: 5 });
    expect(auto.ir.header.warnings.some((w) => w.code === 'dialects-unavailable')).toBe(false);
    session2.dispose();
  });
});
