/*
 * Dependency license report (issue #16; fork/license policy §5.2).
 *
 * Walks the PRODUCTION dependency tree (root package + npm workspaces) via
 * node_modules and reports each package's declared license. Zero dependencies.
 *
 * Usage:
 *   node tools/license-report.mjs           # print a markdown report
 *   node tools/license-report.mjs --check   # exit 1 on unknown or disallowed licenses
 *
 * --check policy: production dependencies must carry a known, MIT-compatible
 * permissive license. Copyleft (GPL/AGPL/LGPL/SSPL/EUPL) or missing licenses fail
 * the check; adding such a dependency requires an explicit policy review
 * (docs/03_UPSTREAM_FORK_LICENSE_AND_CONTRIBUTION_POLICY.md §5, §7).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ALLOWED = new Set(['MIT', 'ISC', 'BSD-2-Clause', 'BSD-3-Clause', 'Apache-2.0', '0BSD', 'Unlicense', 'CC0-1.0']);

function readPkg(dir) {
  try {
    return JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
  } catch {
    return null;
  }
}

/** Resolve a dependency's install dir (flat node_modules first, then nested). */
function resolveDep(name, fromDir) {
  let dir = fromDir;
  for (;;) {
    const candidate = path.join(dir, 'node_modules', name);
    if (fs.existsSync(path.join(candidate, 'package.json'))) return candidate;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

const rows = new Map(); // name@version -> {name, version, license, roots}
const missing = [];

function walk(name, fromDir, root) {
  const dir = resolveDep(name, fromDir);
  if (dir === null) {
    missing.push(`${name} (from ${path.relative(repoRoot, fromDir) || '.'})`);
    return;
  }
  const pkg = readPkg(dir);
  const key = `${pkg.name}@${pkg.version}`;
  if (rows.has(key)) {
    rows.get(key).roots.add(root);
    return;
  }
  const license = typeof pkg.license === 'string' ? pkg.license : (pkg.license?.type ?? 'UNKNOWN');
  rows.set(key, { name: pkg.name, version: pkg.version, license, roots: new Set([root]) });
  for (const dep of Object.keys(pkg.dependencies ?? {})) walk(dep, dir, root);
}

// Roots: the root package and every workspace package.
const rootPkg = readPkg(repoRoot);
const roots = [{ label: rootPkg.name, dir: repoRoot, pkg: rootPkg }];
for (const pattern of rootPkg.workspaces ?? []) {
  const base = path.join(repoRoot, pattern.replace(/\/?\*$/, ''));
  if (!fs.existsSync(base)) continue;
  for (const entry of fs.readdirSync(base)) {
    const dir = path.join(base, entry);
    const pkg = readPkg(dir);
    if (pkg) roots.push({ label: pkg.name, dir, pkg });
  }
}

for (const { label, dir, pkg } of roots) {
  for (const dep of Object.keys(pkg.dependencies ?? {})) walk(dep, dir, label);
}

const sorted = [...rows.values()].sort((a, b) => a.name.localeCompare(b.name));
const bad = sorted.filter((r) => !ALLOWED.has(r.license));

let out = '# Production dependency license report\n\n';
out += `Roots: ${roots.map((r) => `\`${r.label}\``).join(', ')} · Generated by \`tools/license-report.mjs\`\n\n`;
out += '| Package | Version | License | Required by |\n|---|---|---|---|\n';
for (const r of sorted) {
  out += `| ${r.name} | ${r.version} | ${r.license} | ${[...r.roots].join(', ')} |\n`;
}
if (sorted.length === 0) out += '| _none_ | | | |\n';
process.stdout.write(out);

if (missing.length > 0) {
  console.error(`\nWARN: unresolved dependencies (not installed?): ${missing.join('; ')}`);
}

if (process.argv.includes('--check')) {
  if (bad.length > 0 || missing.length > 0) {
    console.error(
      `\nLICENSE CHECK FAILED: ${bad.map((r) => `${r.name}@${r.version} (${r.license})`).join(', ') || 'unresolved deps'}`
    );
    console.error('Production deps must be permissive/MIT-compatible; see policy §5/§7.');
    process.exit(1);
  }
  console.error(`\nLicense check passed: ${sorted.length} production package(s), all permissive.`);
}
