; generated by PrusaSlicer 2.9.2 on 2026-07-27 at 00:00:00 UTC
; Synthetic fixture for DD-016 / #182 — exercises the ;WIPE_START/;WIPE_END bracket convention.
; No private corpus data; hand-authored, MIT, redistributable with the repo test corpus.
G21 ; mm
G90 ; absolute
M83 ; relative E
G92 E0
;TYPE:External perimeter
G1 Z0.2 F600
G1 X10 Y10 F1800
G1 X30 Y10 E1.0
G1 X30 Y30 E1.0
G1 X10 Y30 E1.0
G1 X10 Y10 E1.0
; --- retract + wipe while travelling to the next island ---
;WIPE_START
G1 X12 Y12 E-0.4
G1 X16 Y16 E-0.4
G1 X20 Y20 E-0.2
;WIPE_END
G1 X50 Y50 F9000
;TYPE:Internal infill
G1 X50 Y52 E0.5
G1 X60 Y52 E0.5
G1 X60 Y50 E0.5
